// <auto-generated />
using System;
using Game_Library_Service.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_Library_Service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game_Library_Service.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("User ID who created the entity");

                    b.Property<DateTime>("CreatedDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Date and time when the entity was created");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag - indicates if the entity has been deleted");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("User ID who last updated the entity");

                    b.Property<DateTime?>("ModifiedDateUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the entity was last updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDateUtc")
                        .HasDatabaseName("IX_Game_CreatedAt");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("IX_Game_Deleted");

                    b.HasIndex("Genre")
                        .HasDatabaseName("IX_Games_Genre");

                    b.HasIndex("PublisherId")
                        .HasDatabaseName("IX_Games_PublisherId");

                    b.HasIndex("Deleted", "CreatedDateUtc")
                        .HasDatabaseName("IX_Game_Deleted_CreatedAt");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Game_Library_Service.Data.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("User ID who created the entity");

                    b.Property<DateTime>("CreatedDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("Date and time when the entity was created");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag - indicates if the entity has been deleted");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("User ID who last updated the entity");

                    b.Property<DateTime?>("ModifiedDateUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the entity was last updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDateUtc")
                        .HasDatabaseName("IX_Publisher_CreatedAt");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("IX_Publisher_Deleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Publishers_Name");

                    b.HasIndex("Deleted", "CreatedDateUtc")
                        .HasDatabaseName("IX_Publisher_Deleted_CreatedAt");

                    b.HasIndex("Deleted", "Name")
                        .HasDatabaseName("IX_Publishers_Deleted_Name");

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("Game_Library_Service.Data.Entities.Game", b =>
                {
                    b.HasOne("Game_Library_Service.Data.Entities.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Games_Publishers_PublisherId");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Game_Library_Service.Data.Entities.Publisher", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
